### ISSUE TITLE
macroUUID is not remembered after Streamdeck is quit

### ISSUE THREAD

**Issue by johnsturgeon** [johnofcamas/streamdeck_keyboard_maestro#5]

**Comment by phillipsmn** [comment]
When I paste the UUID into the Macro Button it does not save/persist. The text will and a graphic will, but the actual UUID will not.

**Comment by johnsturgeon** [comment]
That was fixed a week ago. Have you pulled the latest?

**Comment by phillipsmn** [comment]
I downloaded the zip file; assuming it was the latest.

**Comment by johnsturgeon** [comment]
OK, let's do this.. I've enabled some basic logging, but I'm going to update the logging code to specifically log the bits that have to do with persisting the UUID.  After I do that I'll make a note here with specific instructions, and you can grab the latest code, and run it, and attach the log.

**Comment by johnsturgeon** [comment]
Hey @phillipsmn .. I have created a PR #9 with some more detailed logging, I'll attach (here) a zip of that. so you can download the zip file and try it out.
[streamdeck.zip](https://github.com/johnofcamas/streamdeck_keyboard_maestro/files/2898140/streamdeck.zip)

Follow these instructions:

- Delete any current Keyboard Maestro icons you have configured in StreamDeck
- Quit the StreamDeck app
- Delete your current plugin
- Unzip the new one into the same location
- Change the variables in `main.py` to match your virtual environment and plugin location
- Restart the StreamDeck app

You should see a new folder appear in your plugin directory called 'logs', and in it the log file
Follow these instructions then upload the log file

- In StreamDeck App drag the 'Keyboard Maestro' icon to create a new action
- Click on a different icon, or a blank space (de-select the new icon you just added)
- Click *back* on the new Keyboard Maestro icon and type "THIS IS A TEST" in the macroUUID
- Click off the icon again
- Click back on.

If the macroUUID field was cleared, that's a bug, attach the log from that run, if it's there, proceed to these steps:

- Restart the StreamDeck app
- Click on the Keyboard Maestro icon in the app

If the macroUUID field was cleared.. that's a bug.. attach the log.

We'll get this resolved!

**Comment by phillipsmn** [comment]
It looks like that resoved the issue. The macroUUID field persisted throug the process and the plugin is working as expected. 
Great work!

**Comment by johnsturgeon** [comment]
Great, I'll land the latest changes and close this out.
